name: kolki
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^7.0.9
  carousel_pro: ^1.0.0
  charts_flutter: ^0.10.0
  cloud_firestore: ^0.14.0+2
  cupertino_icons: ^1.0.0
  email_validator: ^1.0.4
  english_words: ^3.1.5
  equatable: ^1.1.1
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.2+1
  firebase_storage: ^4.0.0
  flushbar: ^1.10.0
  flutter_barcode_scanner: ^1.0.1
  flutter_bloc: ^6.1.1
  flutter_calendar_carousel: ^1.3.10
  flutter_radio: ^0.1.8
  flutter_spinkit: ^4.1.2+1
  flutter_staggered_animations: ^0.1.2
  flutter_webview_plugin: ^0.3.11
  geolocator: ^5.3.1
  giffy_dialog: ^1.8.0
  google_fonts: ^0.3.10
  hijri: ^2.0.2
  hijri_picker: ^2.0.0
  html: ^0.14.0+3
  http: ^0.12.0+2
  image_picker: ^0.6.4
  intl: ^0.16.1
  json_annotation: ^3.0.0
  json_table: ^1.4.0
  material_design_icons_flutter: ^4.0.5045
  open_file: ^3.0.3
  path: ^1.7.0
  path_provider: ^1.6.18
  pdf: ^2.1.0
  pip_view: ^0.9.5
  provider: 4.3.2+2
  qrscan: ^0.2.17
  rflutter_alert: ^1.1.0
  scoped_model: ^1.0.1
  screenshot: ^0.2.0
  scrollable_list_tabview: ^0.1.6
  share: ^0.6.5+4
  shared_preferences: ^0.5.7+1
  slide_digital_clock: ^1.0.0
  sliding_up_panel: ^1.0.2
  smooth_page_indicator: ^0.2.3
  sqflite: ^1.3.1+1
  table_calendar: ^2.3.3
  url_launcher: ^5.7.10
  webview_flutter: ^1.0.7
  youtube_player_flutter: ^7.0.0+7
  youtube_player_iframe: ^1.2.0+2
  youtube_plyr_iframe: ^1.3.7
  dcdg: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
 # built_value_generator: ^7.0.9
  json_serializable: ^3.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/Montserrat-Regular.ttf
    - assets/Uthmanic-Reguler.otf
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
