import 'dart:convert';
import 'dart:io';
import 'package:hijri/hijri_calendar.dart';
import 'package:kolki/bloc/blocs.dart';
import 'package:kolki/constants.dart';
import 'package:kolki/models/models.dart';
import 'package:kolki/services/services.dart';
import 'package:kolki/shared/shared.dart';
import 'package:kolki/ui/pages/widgets/widgets.dart';
import 'package:email_validator/email_validator.dart';
import 'package:firebase_auth/firebase_auth.dart' as auth;
import 'package:flushbar/flushbar.dart';
import 'package:flutter/material.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:image_picker/image_picker.dart';
import 'package:intl/intl.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:path/path.dart';
import 'package:path_provider/path_provider.dart';
import 'package:provider/provider.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/rendering.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:flutter/gestures.dart';
import 'dart:async';
import 'package:scrollable_list_tabview/scrollable_list_tabview.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:sliding_up_panel/sliding_up_panel.dart';
import 'package:youtube_plyr_iframe/youtube_plyr_iframe.dart';
import 'package:flutter_webview_plugin/flutter_webview_plugin.dart';
import 'package:url_launcher/url_launcher.dart' as url_launcher;
import 'package:giffy_dialog/giffy_dialog.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:open_file/open_file.dart';
import 'package:carousel_pro/carousel_pro.dart';
//import 'package:slide_digital_clock/slide_digital_clock.dart';
import 'dart:math' as math;
import 'package:flutter_calendar_carousel/flutter_calendar_carousel.dart'
    show CalendarCarousel;
import 'package:screenshot/screenshot.dart';
import 'package:share/share.dart';
import 'package:flutter_calendar_carousel/classes/event.dart';
import 'package:flutter_calendar_carousel/classes/event_list.dart';
import 'package:http/http.dart' as http;

import 'package:kolki/youtube_islive.dart';

import 'package:kolki/radio_main.dart';
//import 'package:kolki/ui/pages/pages/aziz_todos_bycategory.dart';
//import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:pip_view/pip_view.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:html/parser.dart' as parser;
import 'package:html/dom.dart' as dom;
import 'package:flutter_staggered_animations/flutter_staggered_animations.dart';
import 'package:flutter/widgets.dart';
import 'package:kolki/shared/shared.dart';
import 'package:kolki/radio_lsit.dart';

//compas
part 'first_page.dart';
part 'sign_in_page.dart';
part 'wrapper.dart';
part 'main_page.dart';
part 'splash_page.dart';
part 'movie_page.dart';
part 'sign_up_page.dart';
part 'preference_page.dart';
part 'account_confirmation_page.dart';
part 'history_page.dart';
part 'library_page.dart';
part 'amal_detail_page.dart';
part 'ilmu_page.dart';
part 'amal_page.dart';
part 'note_list_page.dart';
part 'note_edit_page.dart';
part 'note_view_page.dart';
part 'note_page.dart';
part 'youtube.dart';
//part 'header_content_sholat.dart';
//part 'main_zadwal.dart';
//part 'list_jadwal.dart';
part 'text_style.dart';
part 'ilmu_detail_page.dart';
//part 'ilmu_saja.dart';
//part 'radio.dart';
part 'web_view.dart';
part 'crud.dart';
part 'note_pdf_api.dart';
part 'kiblat.dart';
part 'note_quran.dart';
part 'sumber_ilmu.dart';
part 'web_sumber.dart';
part 'utils.dart';
part '../../../sample_table.dart';
part 'yt_playlist.dart';
part 'yt_home.dart';
part 'tracker_todos_bycategory.dart';
part 'artikel.dart';
part 'reward_collection.dart';
part 'tracker_categories_screen.dart';
part 'tracker_bycategory.dart';
part 'tracker.dart';
part 'tracker_home_screeen.dart';
part 'tracker_todo_screen.dart';
//import 'amal_todo.dart';
//import 'amal_repository.dart';
